'use client';

import { useMemo, useState } from 'react';
import {
  Activity, AlertCircle, ArrowDown, ArrowUp, Bell, Check, ChevronDown, CircleHelp,
  Clock3, Command, Filter, Inbox, LayoutDashboard, ListFilter, MessageSquare,
  MoreHorizontal, Plus, Search, Settings, SlidersHorizontal, Sparkles, Tag, Users,
  X, Zap,
} from 'lucide-react';

type Issue = { id: string; title: string; source: string; sourceTone: string; tag: string; tagTone: string; status: string; statusTone: string; priority: string; priorityTone: string; time: string; assignee: string; initials: string };

const issues: Issue[] = [
  { id: 'FB-1042', title: 'Exporting reports times out for larger workspaces', source: 'Intercom', sourceTone: 'blue', tag: 'Performance', tagTone: 'violet', status: 'In progress', statusTone: 'progress', priority: 'High', priorityTone: 'high', time: '12 min ago', assignee: 'Jordan Lee', initials: 'JL' },
  { id: 'FB-1041', title: 'Add keyboard shortcuts to the command palette', source: 'Slack', sourceTone: 'purple', tag: 'Feature request', tagTone: 'orange', status: 'Open', statusTone: 'open', priority: 'Medium', priorityTone: 'medium', time: '34 min ago', assignee: 'Maya Chen', initials: 'MC' },
  { id: 'FB-1040', title: 'Billing page shows old plan after upgrade', source: 'Zendesk', sourceTone: 'teal', tag: 'Billing', tagTone: 'green', status: 'Open', statusTone: 'open', priority: 'High', priorityTone: 'high', time: '1 hr ago', assignee: 'Unassigned', initials: '—' },
  { id: 'FB-1039', title: 'Mobile navigation overlaps the feedback button', source: 'In-app', sourceTone: 'pink', tag: 'Usability', tagTone: 'blue', status: 'Resolved', statusTone: 'resolved', priority: 'Low', priorityTone: 'low', time: '2 hrs ago', assignee: 'Sam Rivera', initials: 'SR' },
  { id: 'FB-1038', title: 'Users need a way to pause notification emails', source: 'Intercom', sourceTone: 'blue', tag: 'Feature request', tagTone: 'orange', status: 'In progress', statusTone: 'progress', priority: 'Medium', priorityTone: 'medium', time: '3 hrs ago', assignee: 'Alex Morgan', initials: 'AM' },
];

const navItems = [
  { label: 'Overview', icon: LayoutDashboard, active: true },
  { label: 'Inbox', icon: Inbox, count: '24' },
  { label: 'All feedback', icon: MessageSquare },
  { label: 'Issues', icon: AlertCircle, count: '8' },
];

function Badge({ children, tone }: { children: React.ReactNode; tone: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Avatar({ initials, small = false }: { initials: string; small?: boolean }) { return <span className={`avatar ${small ? 'small' : ''}`}>{initials}</span>; }

export default function Dashboard() {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All feedback');
  const [notice, setNotice] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [showFilters, setShowFilters] = useState(false);
  const filteredIssues = useMemo(() => issues.filter((issue) => issue.title.toLowerCase().includes(query.toLowerCase()) && (filter === 'All feedback' || issue.status === filter)), [query, filter]);

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'mobile-open' : ''}`}>
      <div className="brand"><span className="brand-mark"><Sparkles size={15} /></span><span>feedback<span className="brand-accent">desk</span></span></div>
      <div className="workspace-switcher"><div className="workspace-icon">AC</div><div><strong>Acme Corp</strong><span>Product workspace</span></div><ChevronDown size={15} /></div>
      <nav aria-label="Main navigation"><p className="nav-label">WORKSPACE</p>{navItems.map(({ label, icon: Icon, active, count }) => <button key={label} className={`nav-item ${active ? 'active' : ''}`} onClick={() => setFilter(label === 'Issues' ? 'Open' : 'All feedback')}><Icon size={17} /><span>{label}</span>{count && <em>{count}</em>}</button>)}<p className="nav-label section-label">MANAGE</p><button className="nav-item"><Tag size={17} /><span>Tags</span></button><button className="nav-item"><Users size={17} /><span>Team</span></button><button className="nav-item"><Activity size={17} /><span>Insights</span></button></nav>
      <div className="sidebar-bottom"><button className="nav-item"><Settings size={17} /><span>Settings</span></button><div className="profile"><Avatar initials="KM" /><div><strong>Kate Miller</strong><span>Admin</span></div><MoreHorizontal size={16} /></div></div>
    </aside>
    {mobileNav && <button className="scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)} />}
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Command size={19} /></button><div className="breadcrumbs"><span>Workspace</span><span>/</span><strong>Overview</strong></div><div className="top-actions"><button className="icon-button" aria-label="Help"><CircleHelp size={19} /></button><button className="icon-button notification" aria-label="Notifications" onClick={() => setNotice(!notice)}><Bell size={19} /><i /></button><div className="top-avatar"><Avatar initials="KM" /></div></div></header>
      {notice && <div className="notification-popover"><strong>Notifications</strong><p>3 new feedback items need triage.</p><button onClick={() => setNotice(false)}>Dismiss</button></div>}
      <div className="page-wrap"><section className="page-heading"><div><p className="eyebrow">THURSDAY, OCTOBER 24, 2024</p><h1>Good morning, Kate <span>✦</span></h1><p className="subtitle">Here&apos;s what&apos;s happening with your customer feedback.</p></div><button className="primary-button"><Plus size={17} /> New issue</button></section>
        <section className="metric-grid" aria-label="Feedback metrics"><Metric label="Total feedback" value="1,284" change="12.5%" detail="vs. last month" up icon={<MessageSquare size={18} />} /><Metric label="Open issues" value="24" change="8.2%" detail="vs. last week" icon={<AlertCircle size={18} />} /><Metric label="Avg. response time" value="4h 12m" change="18.4%" detail="vs. last month" up icon={<Clock3 size={18} />} /><Metric label="Resolution rate" value="84.6%" change="5.7%" detail="vs. last month" up icon={<Zap size={18} />} /></section>
        <section className="insight-grid"><div className="panel trend-panel"><div className="panel-heading"><div><h2>Feedback volume</h2><p>Incoming feedback over the last 30 days</p></div><button className="select-button">Last 30 days <ChevronDown size={14} /></button></div><div className="chart-legend"><span><i className="legend-dot blue-dot" />Total feedback</span><span><i className="legend-dot violet-dot" />Issues created</span></div><div className="chart"><div className="y-axis"><span>120</span><span>80</span><span>40</span><span>0</span></div><div className="chart-area"><div className="grid-lines"><i /><i /><i /><i /></div><svg viewBox="0 0 700 210" preserveAspectRatio="none" role="img" aria-label="Feedback volume trend chart"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#3468f5" stopOpacity=".19" /><stop offset="100%" stopColor="#3468f5" stopOpacity="0" /></linearGradient></defs><path d="M0,142 C32,130 50,155 76,137 S120,111 145,125 S181,143 205,113 S247,98 270,110 S310,85 338,99 S379,129 405,102 S448,73 475,83 S512,102 536,68 S571,75 596,58 S635,77 662,42 S683,58 700,31 L700,210 L0,210 Z" fill="url(#area)" /><path d="M0,142 C32,130 50,155 76,137 S120,111 145,125 S181,143 205,113 S247,98 270,110 S310,85 338,99 S379,129 405,102 S448,73 475,83 S512,102 536,68 S571,75 596,58 S635,77 662,42 S683,58 700,31" fill="none" stroke="#3468f5" strokeWidth="3" /><path d="M0,178 C32,170 50,183 76,170 S120,155 145,167 S181,171 205,159 S247,153 270,163 S310,141 338,151 S379,169 405,153 S448,132 475,145 S512,150 536,128 S571,138 596,119 S635,137 662,111 S683,119 700,103" fill="none" stroke="#8c6af5" strokeWidth="2.5" strokeDasharray="5 5" /></svg><div className="x-axis"><span>Sep 25</span><span>Oct 1</span><span>Oct 7</span><span>Oct 13</span><span>Oct 19</span><span>Oct 24</span></div></div></div></div>
          <div className="panel sources-panel"><div className="panel-heading"><div><h2>Feedback sources</h2><p>Where your feedback comes from</p></div><button className="more-button" aria-label="More options"><MoreHorizontal size={19} /></button></div><div className="source-list"><Source label="In-app widget" value="486" percent="38%" color="blue" /><Source label="Intercom" value="342" percent="27%" color="violet" /><Source label="Slack" value="231" percent="18%" color="orange" /><Source label="Zendesk" value="148" percent="12%" color="teal" /><Source label="Other" value="77" percent="6%" color="gray" /></div><button className="text-button">View source report <ArrowUp size={14} /></button></div></section>
        <section className="panel issues-panel"><div className="issues-heading"><div><h2>Recent feedback &amp; issues</h2><p>Stay on top of what needs your attention.</p></div><button className="secondary-button" onClick={() => setShowFilters(!showFilters)}><SlidersHorizontal size={16} /> Filters {showFilters && <X size={14} />}</button></div><div className="table-toolbar"><div className="search-box"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search feedback or issues..." aria-label="Search feedback or issues" /></div><div className="toolbar-right"><button className={`filter-button ${filter !== 'All feedback' ? 'selected' : ''}`} onClick={() => setFilter(filter === 'All feedback' ? 'Open' : 'All feedback')}><ListFilter size={15} /> {filter}<ChevronDown size={14} /></button><button className="filter-button"><Filter size={15} /> Sort: Recent <ChevronDown size={14} /></button></div></div>{showFilters && <div className="filter-note"><span>Showing {filter === 'All feedback' ? 'all feedback' : 'open items'}</span><button onClick={() => { setFilter('All feedback'); setShowFilters(false); }}>Clear filters <X size={13} /></button></div>}<div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select all issues" /></th><th>FEEDBACK / ISSUE</th><th>SOURCE</th><th>TAG</th><th>STATUS</th><th>PRIORITY</th><th>ASSIGNEE</th><th></th></tr></thead><tbody>{filteredIssues.map((issue) => <tr key={issue.id}><td><input type="checkbox" aria-label={`Select ${issue.id}`} /></td><td><div className="issue-title"><strong>{issue.title}</strong><span>{issue.id} · {issue.time}</span></div></td><td><Badge tone={`source-${issue.sourceTone}`}>{issue.source}</Badge></td><td><Badge tone={`tag-${issue.tagTone}`}>{issue.tag}</Badge></td><td><Badge tone={issue.statusTone}><i className="status-dot" />{issue.status}</Badge></td><td><Badge tone={issue.priorityTone}>{issue.priority}</Badge></td><td><div className="assignee"><Avatar initials={issue.initials} small /><span>{issue.assignee}</span></div></td><td><button className="row-more" aria-label={`More actions for ${issue.id}`}><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table>{filteredIssues.length === 0 && <div className="empty-state">No feedback matches your search.</div>}</div><div className="table-footer"><span>Showing 1–{filteredIssues.length} of 1,284 feedback items</span><div><button disabled>Previous</button><button className="page-active">1</button><button>2</button><button>3</button><button>Next <ArrowDown size={13} /></button></div></div></section>
      </div>
    </main>
  </div>;
}

function Metric({ label, value, change, detail, up = false, icon }: { label: string; value: string; change: string; detail: string; up?: boolean; icon: React.ReactNode }) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><div className="metric-change"><span className={up ? 'positive' : 'negative'}>{up ? <ArrowUp size={13} /> : <ArrowDown size={13} />}{change}</span><span>{detail}</span></div></div> }
function Source({ label, value, percent, color }: { label: string; value: string; percent: string; color: string }) { return <div className="source-row"><span className={`source-icon ${color}`}><Activity size={14} /></span><span className="source-label">{label}</span><div className="source-bar"><i className={color} style={{ width: percent }} /></div><strong>{value}</strong><span className="source-percent">{percent}</span></div> }
